repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0 # Use the latest stable version
    hooks:
      - id: no-commit-to-branch
        args: ["--branch", "main", "--branch", "master"]
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: dart-fix
        name: dart fix
        entry: scripts/dart-fix.sh
        language: script
        types: [dart]
        exclude: ^packages/soliplex_client/lib/src/schema/
      - id: dart-format
        name: dart format
        entry: scripts/dart-format.sh --set-exit-if-changed
        language: script
        types: [dart]
        exclude: ^packages/soliplex_client/lib/src/schema/
      - id: flutter-analyze
        name: flutter analyze
        entry: scripts/flutter-analyze.sh --fatal-infos
        language: script
        types: [dart]
        pass_filenames: false
      - id: dart-analyze-packages
        name: dart analyze packages
        entry: python3 tool/analyze_packages.py
        language: system
        pass_filenames: false
