name: soliplex_logging
description: Central logging package for Soliplex applications.
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  http: ^1.2.0
  meta: ^1.9.0

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^7.0.0
